### PR TITLE
Add initial version of a pam_flux module

### PR DESCRIPTION
**Pull request by grondo**
Add an initial version of pam_flux.c, including autotools build
infrastructure, sharness-based tests, and GitHub workflow.

### CODE REVIEW

**Comment by grondo** [comment]
This will need to be merged manually since no mergify config exists yet. Also, hopefully workflows will start running after this is merged as well. After that all checks out I'll make an initial tag.

**Comment by garlick** [comment]
Ooh nice!

What provides `libpam_wrapper.so`?   When I run the sharness test I'm getting 
```
ERROR: ld.so: object 'libpam_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
however the tests are all passing except this one:
```
expecting success: 
	jobid=$(flux mini submit --wait-event=alloc sleep 300) &&
	pamtest -u ${USER}

ERROR: ld.so: object 'libpam_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
pamtest: pam_start ("pam-test", "garlick", misc_conv, &pamh)
pamtest: pam_set_item (pamh, PAM_USER, "garlick")
pamtest: pam_set_item (pamh, PAM_RUSER, "garlick")
pamtest: pam_set_item (pamh, PAM_HOST, "system76-pc")
pamtest: pam_authenticate (pamh, 0)
Password: pamtest: User garlick not authorized. rc=7
not ok 3 - pam_flux: module allows access with a job running
#	
#		jobid=$(flux mini submit --wait-event=alloc sleep 300) &&
#		pamtest -u ${USER}
#	
```

**Comment by grondo** [comment]
Oh oops, that was sloppy. `pam_wrapper` is from the [cwrap](https://cwrap.org/pam_wrapper.html) project (part of samba), and allows simulating running the PAM stack from a standalone application without modifying the actual PAM stack. It is currently pulled in to CI, and `make check` should be disabled if `libpamtest.so` isn't found at configure time.

However, there's also a problem here that the expected test failures fail when `pam_wrapper.so` isn't installed, which is why most of the tests still succeed. We'll need some way to work around that.

**Comment by grondo** [comment]
Ok, I've updated some things in this PR related to the testing goofs

 - The test program no longer uses libpamtest, so drop that requirement and check from configure
 - Check that `libpam_wrapper.so` can be preloaded and skip all tests if not
 - Exit with an error if the `pamtest` program isn't built

**Comment by grondo** [comment]
Example CI checks runs are in my fork [here](https://github.com/grondo/flux-pam/actions/runs/2569978788).
I think the checks will start running after the first merge. That will be verified by a subsequent PR with a new NEWS entry for an initial tag.

**Review by cmoussa1 — APPROVED** [review]
FWIW, the general repo files (README, Dockerfiles, etc.) LGTM! I'm sorry that I'm not knowledgeable enough about the PAM module stuff to be able to review it very well. Just one question - does this repo also need the `generate-matrix.py` file used in other flux-framework projects for GitHub actions? I could be looking in the wrong place but I don't see that file in this PR.

**Review by garlick — APPROVED** [review]
LGTM!

I didn't spend the time to review PAM, which I would need to do to give more than a superficial review, but maybe it's best to get this first PR merged and go from there.

**Comment by grondo** [comment]
Thanks, can one of you press the button? :-)

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
