### PR TITLE
doc: add `pam_flux(8)` man page

### PR DESCRIPTION
**Pull request by grondo**
This PR adds the minimum sphinx doc infrastructure and a `pam_flux(8)` man page.

It is built on top of #8

### CODE REVIEW

**Review by garlick — APPROVED** [review]
LGTM!

We should probably try to publish this to readthedocs like the other projects so we can do stuff like link to this  man page from the admin guide.  I can research that and propose a follow on PR.

**Comment by grondo** [comment]
Thanks! I started to go down that rabbit hole but thought getting a man page packaged was a good first step.

**Comment by garlick** [comment]
Agreed!  I need to do it for flux-pmix too so maybe I'll just do a 2fer.

**Comment by grondo** [comment]
Rebased and set MWP.

**Pull request merged**
